[development.logging_ansible_deploy]
version = 1

[development.logging_ansible_deploy.formatters.default]
format = "%(asctime)s %(levelname)-8s [%(filename)s:%(lineno)s] %(message)s"

[development.logging_ansible_deploy.loggers.ansible_deploy]
handlers = ["service_file"]
level = "DEBUG"

[development.logging_ansible_deploy.handlers.service_file]
class = "logging.handlers.RotatingFileHandler"
filename = ""
maxBytes = 10485760
backupCount = 4
formatter = "default"
level = "DEBUG"


[production.logging_ansible_deploy]
version = 1

[production.logging_ansible_deploy.formatters.default]
format = "%(asctime)s %(levelname)-8s [%(filename)s:%(lineno)s] %(message)s"

[production.logging_ansible_deploy.loggers.ansible_deploy]
handlers = ["service_file"]
level = "DEBUG"

[production.logging_ansible_deploy.handlers.service_file]
class = "logging.handlers.RotatingFileHandler"
filename = ""
maxBytes = 10485760
backupCount = 4
formatter = "default"
level = "DEBUG"
