---
- name: Docker installation
  hosts: "{{ host_pattern }}"
  become: true
  gather_facts: true

  tasks:
    - block:
      - name: Install required system packages
        ansible.builtin.package:
          name: "{{ docker_dependency }}"
          update_cache: yes
          state: latest
        loop:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        loop_control:
          loop_var: docker_dependency

      - name: Add Docker GPG apt Key
        ansible.builtin.apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

      - name: Add Docker Repository
        ansible.builtin.apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present

      - name: Update apt and install docker-ce
        ansible.builtin.apt:
          name: "{{ item }}"
          state: latest
          update_cache: yes
        loop:
          - docker-ce
          - docker-ce-cli
          - containerd.io

      - name: Install Docker Module for Python
        ansible.builtin.pip:
          name: docker

      - name: Run and enable docker
        ansible.builtin.service:
          name: docker
          state: started
          enabled: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Fail when target os_family not supported
      ansible.builtin.fail:
        msg: Unsupported OS — '{{ ansible_facts['os_family'] }}'
      ignore_errors: true
      when: ansible_facts['os_family'] != 'Debian'
