"""table

Revision ID: 1996d39c4020
Revises: 1574e72b7af2
Create Date: 2023-04-21 21:26:19.117385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1996d39c4020'
down_revision = '1574e72b7af2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
