"""table1

Revision ID: a22cb616c819
Revises: 1996d39c4020
Create Date: 2023-04-21 21:46:53.990982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22cb616c819'
down_revision = '1996d39c4020'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
