"""table2

Revision ID: ea09dcdd2f6c
Revises: a22cb616c819
Create Date: 2023-04-21 21:56:47.995966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea09dcdd2f6c'
down_revision = 'a22cb616c819'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
