"""table

Revision ID: 08f0d73cfd2c
Revises: a137f63c2127
Create Date: 2023-04-21 20:32:07.486313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f0d73cfd2c'
down_revision = 'a137f63c2127'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
