"""table_4

Revision ID: 0b9e25fd16a9
Revises: c77d0f48518e
Create Date: 2023-04-26 21:53:02.995083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9e25fd16a9'
down_revision = 'c77d0f48518e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
