"""initial

Revision ID: 75f62829631f
Revises: 
Create Date: 2023-05-21 10:22:11.998198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f62829631f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('short_desсription', sa.String(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('users_first_name', sa.String(), nullable=False),
    sa.Column('users_last_name', sa.String(), nullable=False),
    sa.Column('users_mail', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('users_id')
    )
    op.create_table('client_request',
    sa.Column('client_request_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_phone', sa.String(), nullable=True),
    sa.Column('client_mail', sa.String(), nullable=False),
    sa.Column('client_message', sa.String(), nullable=False),
    sa.Column('theme', sa.Integer(), nullable=False),
    sa.Column('request_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['theme'], ['service.service_id'], ),
    sa.PrimaryKeyConstraint('client_request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_request')
    op.drop_table('users')
    op.drop_table('service')
    # ### end Alembic commands ###
