"""table_007

Revision ID: 8b9aeeb92077
Revises: 0d8b163f2e46
Create Date: 2023-04-27 13:43:18.027820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9aeeb92077'
down_revision = '0d8b163f2e46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
