"""table_009

Revision ID: 9446d328d7a3
Revises: c339c7409246
Create Date: 2023-05-17 20:48:38.651219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9446d328d7a3'
down_revision = 'c339c7409246'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagegroups')
    op.drop_constraint('news_img_grop_fkey', 'news', type_='foreignkey')
    op.drop_column('news', 'img_grop')
    op.drop_constraint('service_img_grop_fkey', 'service', type_='foreignkey')
    op.drop_column('service', 'img_grop')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('img_grop', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('service_img_grop_fkey', 'service', 'imagegroups', ['img_grop'], ['name'])
    op.add_column('news', sa.Column('img_grop', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('news_img_grop_fkey', 'news', 'imagegroups', ['img_grop'], ['name'])
    op.create_table('imagegroups',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url_group', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='imagegroups_pkey')
    )
    # ### end Alembic commands ###
