"""tab_01

Revision ID: 959ee02cfa83
Revises: 75f62829631f
Create Date: 2023-05-23 17:20:23.317533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '959ee02cfa83'
down_revision = '75f62829631f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_requests',
    sa.Column('client_request_uid', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_phone', sa.String(), nullable=True),
    sa.Column('client_mail', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('tittle', sa.String(), nullable=False),
    sa.Column('request_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('client_request_uid'),
    sa.UniqueConstraint('client_request_uid')
    )
    op.create_table('trade_items',
    sa.Column('trade_items_uid', sa.String(), nullable=False),
    sa.Column('trade_items_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('short_desсription', sa.String(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('trade_items_uid'),
    sa.UniqueConstraint('trade_items_uid')
    )
    op.drop_table('client_request')
    op.drop_table('service')
    op.add_column('users', sa.Column('user_uid', sa.String(), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('mail', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['user_uid'])
    op.drop_column('users', 'users_last_name')
    op.drop_column('users', 'users_id')
    op.drop_column('users', 'users_first_name')
    op.drop_column('users', 'users_mail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('users_mail', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('users_first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('users_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('users_last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'mail')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'user_uid')
    op.create_table('service',
    sa.Column('service_id', sa.INTEGER(), server_default=sa.text("nextval('service_service_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('short_desсription', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('service_id', name='service_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('client_request',
    sa.Column('client_request_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_mail', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('theme', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('request_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['theme'], ['service.service_id'], name='client_request_theme_fkey'),
    sa.PrimaryKeyConstraint('client_request_id', name='client_request_pkey')
    )
    op.drop_table('trade_items')
    op.drop_table('client_requests')
    # ### end Alembic commands ###
