"""tab_05

Revision ID: 9f8a6988f61d
Revises: ff8e56e7ef68
Create Date: 2023-05-25 11:02:23.738520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8a6988f61d'
down_revision = 'ff8e56e7ef68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
