"""tab_03

Revision ID: a3cf5fe3cc71
Revises: d8b994d20f33
Create Date: 2023-05-23 22:41:58.807017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cf5fe3cc71'
down_revision = 'd8b994d20f33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_items', sa.Column('short_description', sa.String(), nullable=False))
    op.drop_column('trade_items', 'short_desсription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_items', sa.Column('short_desсription', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('trade_items', 'short_description')
    # ### end Alembic commands ###
