"""table_008

Revision ID: c339c7409246
Revises: 8b9aeeb92077
Create Date: 2023-04-27 17:24:58.500461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c339c7409246'
down_revision = '8b9aeeb92077'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagegroups',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('url_group', postgresql.ARRAY(
                        sa.String()), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('name'),
                    sa.UniqueConstraint('name')
                    )
    op.drop_table('image')
    status_enum = postgresql.ENUM(
        'received', 'discussed', 'in progress', 'closed', name='status_enum')
    status_enum.create(op.get_bind())
    op.add_column('client_request', sa.Column('status', sa.Enum(
        'received', 'discussed', 'in progress', 'closed', name='status_enum'), nullable=False))
    vstatus_enum = postgresql.ENUM(
        'visible', 'invsible', name='vstatus_enum')
    vstatus_enum.create(op.get_bind())
    op.add_column('news', sa.Column('status', sa.Enum(
        'visible', 'invsible', name='vstatus_enum'), nullable=False))
    op.add_column('news', sa.Column('img_grop', sa.String(), nullable=False))
    op.create_foreign_key(None, 'news', 'imagegroups', ['img_grop'], ['name'])
    op.add_column('service', sa.Column('status', sa.Enum(
        'visible', 'invsible', name='vstatus_enum'), nullable=False))
    op.add_column('service', sa.Column(
        'img_grop', sa.String(), nullable=False))
    op.create_foreign_key(None, 'service', 'imagegroups',
                          ['img_grop'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_column('service', 'img_grop')
    op.drop_column('service', 'status')
    status_enum = postgresql.ENUM(
        'received', 'discussed', 'in progress', 'closed', name='status_enum')
    status_enum.create(op.get_bind())
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'img_grop')
    op.drop_column('news', 'status')
    op.drop_column('client_request', 'status')
    vstatus_enum = postgresql.ENUM(
        'visible', 'invsible', name='vstatus_enum')
    vstatus_enum.create(op.get_bind())
    op.create_table('image',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('url', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='image_pkey')
                    )
    op.drop_table('imagegroups')
    # ### end Alembic commands ###
