"""table_5

Revision ID: d1d730661167
Revises: 0b9e25fd16a9
Create Date: 2023-04-26 21:56:28.390462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1d730661167'
down_revision = '0b9e25fd16a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_img')
    op.drop_table('services_img')
    op.drop_constraint('client_request_status_fkey', 'client_request', type_='foreignkey')
    op.drop_column('client_request', 'status')
    op.drop_constraint('news_status_fkey', 'news', type_='foreignkey')
    op.drop_column('news', 'status')
    op.drop_constraint('service_status_fkey', 'service', type_='foreignkey')
    op.drop_column('service', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('service_status_fkey', 'service', 'visible_status', ['status'], ['id'])
    op.add_column('news', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('news_status_fkey', 'news', 'visible_status', ['status'], ['id'])
    op.add_column('client_request', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('client_request_status_fkey', 'client_request', 'card_status', ['status'], ['id'])
    op.create_table('services_img',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name='services_img_image_id_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name='services_img_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='services_img_pkey')
    )
    op.create_table('news_img',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name='news_img_image_id_fkey'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name='news_img_news_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='news_img_pkey')
    )
    # ### end Alembic commands ###
