"""table1

Revision ID: d8034c9687ec
Revises: 08f0d73cfd2c
Create Date: 2023-04-21 20:38:45.261559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8034c9687ec'
down_revision = '08f0d73cfd2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
