"""tab_02

Revision ID: d8b994d20f33
Revises: 959ee02cfa83
Create Date: 2023-05-23 21:40:17.942426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b994d20f33'
down_revision = '959ee02cfa83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_items', sa.Column('trade_item_uid', sa.String(), nullable=False))
    op.add_column('trade_items', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('trade_items', 'trade_items_name')
    op.drop_column('trade_items', 'trade_items_uid')
    op.drop_constraint('users_user_uid_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_user_uid_key', 'users', ['user_uid'])
    op.add_column('trade_items', sa.Column('trade_items_uid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('trade_items', sa.Column('trade_items_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('trade_items', 'name')
    op.drop_column('trade_items', 'trade_item_uid')
    # ### end Alembic commands ###
