"""tab_04

Revision ID: ff8e56e7ef68
Revises: a3cf5fe3cc71
Create Date: 2023-05-24 16:51:52.401251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8e56e7ef68'
down_revision = 'a3cf5fe3cc71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
