[development.deploy]
mode='development'

[development.deploy.nginx]
image_name = 'nginx-custom'
container_name = 'kreoshine-nginx'

[production.deploy]
mode='production'

[production.deploy.nginx]
image_name = 'nginx-custom'
container_name = 'kreoshine-nginx'
