name: Pylint

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f backend/pip-freeze.txt ]; 
        then pip install -r backend/requirements.txt; fi
        if [ -f deploy/pip-freeze.txt ]; then pip install -r deploy/pip-freeze.txt; fi
        if [ -f backend/app/services/index/pip-freeze.txt ]; 
        then pip install -r backend/app/services/index/pip-freeze.txt; fi
    - name: Analysing the code with pylint
      run:
        pylint
          --ignore=backend/alembic/versions/
          --max-line-length=120 
          --init-hook="import sys; sys.path.append('backend/app/services/index')" 
          $(git ls-files '*.py')
          